### ISSUE TITLE
Help to index this package into godoc

### ISSUE THREAD

**Issue by mufti1** [mufti1/interconv#8]
help me how to index this library into golang documentation in godoc.org

**Comment by empijei** [comment]
[https://godoc.org/github.com/mufti1/interconv/package](https://godoc.org/github.com/mufti1/interconv/package) isn't it already there?

**Comment by mufti1** [comment]
I see can you make it to just /interconv? @empijei

**Comment by budougumi0617** [comment]
If you show  the documents in `/interconv` PATH, you should move `*.go` files from `/interconv/package` direcotry to  `/interconv` directory. gdoc.org show documents just as file path.

Other solution:
Usually, we writes package documents in `doc.go`, and put it to directory. 
For example, `doc.go` of `aws-sdk-go` is below,

https://github.com/aws/aws-sdk-go/blob/master/doc.go
https://godoc.org/github.com/aws/aws-sdk-go

**Comment by mufti1** [comment]
Thankyou i will make it
